### ISSUE TITLE
Why is the Client Characteristic Configuration Descriptor explicitly not allowed?

### ISSUE THREAD

**Issue by dustin-graham** [Polidea/MultiPlatformBleAdapter#55]
Hello,
I'm trying to work with  a bluetooth service which explicitly requires that my app write to this descriptor (2902) to enable notifications for certain characteristics. I found that I was getting a 506 denied error and went looking through the source code. I found the change was introduced on this PR:
https://github.com/Polidea/MultiPlatformBleAdapter/pull/40/files

https://github.com/Polidea/MultiPlatformBleAdapter/blob/883ea0802867b86fb1a63776dde584de68c125f8/iOS/classes/BleModule.swift#L1166

is the line which disables this functionality. I've not been able to find documentation online that suggests this be a recommended behavior for a BLE client library. Is there a reason why this is not allowed?

**Comment by mikolak** [comment]
Hi,

To turn on notifications/indications you should use `Characteristic.monitor()` or `(Service/Peripheral).monitorCharacteristic()`.

AFAIK it's because OS does not allow you to manipulate that value manually and instead forces you to use https://developer.apple.com/documentation/corebluetooth/cbperipheral/1518949-setnotifyvalue

I'm not an expert on iOS though. 

Let me know if it helped.

**Comment by dustin-graham** [comment]
I am calling monitor on the characteristic, however, my peripheral won't
send data unless I write to this descriptor first. It's just the way the
peripheral is built. I'm basing my Flutter implementation off of an
existing iOS implementation which definitely does write to this descriptor.
I'm going to experiment tonight on my fork of the project to see if I can
make it work by simply commenting out that check. I will let you know what
I find. But as far as I can tell from the documentation I've read so far,
this check is unnecessary. If you have any additional details to provide
please let me know. Thanks for the great work on the lib!

**Comment by mikolak** [comment]
`Characteristic.monitor()` in fact writes `1` to that descriptor AFAIK, just not using descriptor API but the system's `setNotifyValue` or its Android counterpart.

(it also writes 0 once you stop listening to the stream)

**Comment by dustin-graham** [comment]
Oh, that's good to know. Thank you.
