### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by yaeda** [Polidea/MultiPlatformBleAdapter#63]
I want to use this library in the macOS app.
Do you have any plans to support it?

**Comment by mikolak** [comment]
Hi! We're thinking about it, but haven't yet investigated this.

I think there's a community PR with some of it, but I'm not knowledgeable enough about iOS and macOS. I'll try to have someone more appropriate have a look at the requirements.

**Comment by yaeda** [comment]
Thank you for sharing your thoughts. Polidea/RxBluetoothKit seems to support macOS as well, so I'm hoping this will be the same.
